---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# bactcountr

<!-- badges: start -->
<!-- badges: end -->

The goal of bactcountr is to provide an automated way to calculate CFUs based on the dilutions used and to plot the final results.

## Installation

You can install the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("aef1004/bactcountr")
```
## Example

This is a basic example which shows you how to solve a common problem:

```{r message = FALSE}
library(bactcountr)

library(dplyr)
library(tidyr)
library(ggplot2)
library(ggbeeswarm)
## basic example code
```


```{r}
CFU_raw_formatted <- tidy_CFU(CFU_excel_raw, "CFUs")

CFU_one_dilution <- pick_one_dilution(CFU_raw_formatted, "CFUs", c("group", "organ", "mouse"))

calculate_cfu(CFU_one_dilution, 5, 0.5, .5, "dilution", "CFUs")
```


```{r warning = FALSE}

analyzed_CFUs <- tidy_CFU(CFU_excel_raw, "CFUs") %>%
  pick_one_dilution("CFUs", c("group", "organ", "mouse")) %>%
  filter(organ == "Spleen") %>%
  calculate_cfu(5, 0.5, .5, "dilution", "CFUs")


ggplot(analyzed_CFUs, aes(group, log_CFUs, color = group)) +
  geom_beeswarm(groupOnX = TRUE) +
  ggtitle("PL BCG CFUs D-21 Spleen")

```

